'use client'

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/styles/globals.css";

import { useEffect } from "react";
import { auth } from "@/lib/firebase";
import { onAuthStateChanged, getIdToken } from "firebase/auth";
import { setCookie, deleteCookie } from "cookies-next";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

// export const metadata: Metadata = {
//   title: "Matcheo",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (user) => {
      if (user) {
        const token = await getIdToken(user, true);
        setCookie("__session", token);
      } else {
        deleteCookie("__session");
      }
    });

    return () => unsubscribe();
  }, []);


  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
